### ISSUE TITLE
Fix code formatting + configure linter

### ISSUE THREAD

**Issue by spanic** [komrade2801/NC_Spring#2]
After adding Webpack boilerplate from https://github.com/komrade2801/NC_Spring/issues/1, please configure [ESLint](https://eslint.org/) and [Prettier](https://prettier.io/), then reformat all of your code using these plugins

**Comment by spanic** [comment]
You can also install [StandartJS](https://standardjs.com/) package instead of the tools mentioned above and forget about the .eslintrc configuration

**Comment by komrade2801** [comment]
Done, though without a template
